# PostgreSQL
#   Ensure the PostgreSQL gem is defined in your Gemfile
#   gem 'pg'
development:
  adapter: postgresql
  encoding: utf8
  database: railsbricks_3342_development
  username: postgres
  password: 123
  host: localhost
  pool: 5
  port: 5432
